#!/usr/bin/env python3
"""
ABS scenario validation — data-rich engineering report.

Reads the four ABS-test summary.txt + CSV outputs produced by
run_abs_compare.sh, computes per-wheel and per-axle statistics,
generates inline SVG charts (vehicle speed, wheel speeds, slip
ratios, ABS phase Gantt timeline, yaw rate, trajectory), and
writes a single markdown memo with everything embedded.

Usage:
    ./scripts/abs_report.py <output.md>

The script discovers data under /tmp/ev1sim_abs_<test>/ for each
of the four standard scenarios (high_mu, low_mu, mu_jump,
split_mu).  Re-run scripts/run_abs_compare.sh first to refresh
the source data.

SVG charts are written to a sibling directory of the output md
(e.g. <output>.charts/) and referenced by relative path.  No
matplotlib dependency — SVG is generated by hand with simple
polyline / rect / text primitives so the report renders cleanly
in any markdown viewer.
"""

from __future__ import annotations

import csv
import datetime
import re
import sys
from pathlib import Path
from typing import Optional

TESTS = ["high_mu", "low_mu", "mu_jump", "split_mu"]
SUMMARY_DIR_TMPL = "/tmp/ev1sim_abs_{test}"

# Tire radius used by the chassis side (matches firmware default now).
TIRE_RADIUS_M = 0.2915

# Test-setup metadata (configuration the user wants surfaced up front).
SETUP = {
    "high_mu": {
        "surface":    "uniform asphalt (μ ≈ 0.9)",
        "approach":   "throttle to ≥ 30 m/s, throttle off, full brake",
        "brake_at":   "scenario t = 6 s",
        "checks":     "ABS should mostly stay quiet; wheel lock on dry asphalt is rare",
    },
    "low_mu": {
        "surface":    "uniform ice (μ ≈ 0.10)",
        "approach":   "throttle to ≥ 15 m/s, throttle off, full brake",
        "brake_at":   "scenario t = 7 s",
        "checks":     "wheels lock easily; ABS should modulate and keep wheels rolling",
    },
    "mu_jump": {
        "surface":    "asphalt for 100 m, then ice (μ jumps from 0.9 → 0.08)",
        "approach":   "throttle to ≥ 20 m/s on asphalt, throttle off, full brake — typically straddles or has just crossed onto ice when brake hits",
        "brake_at":   "scenario t = 6 s",
        "checks":     "algorithm must adapt as friction drops mid-event",
    },
    "split_mu": {
        "surface":    "left side asphalt (μ = 0.9), right side ice (μ = 0.08)",
        "approach":   "throttle to ≥ 20 m/s straddling the seam, throttle off, full brake",
        "brake_at":   "scenario t = 12 s",
        "checks":     "yaw stability — without per-wheel ABS the asphalt-side wheels brake while ice-side skids, generating a yaw moment",
    },
}


# ---------------------------------------------------------------------------
# Parse the run_abs_compare.sh summary.txt files
# ---------------------------------------------------------------------------

def parse_summary(text: str) -> dict:
    out: dict = {"on_stopped": False, "off_stopped": False}
    section = None
    for line in text.splitlines():
        s = line.strip()
        if "BTCM-on" in s and "===" in s:
            section = "on"
        elif "BTCM-off" in s and "===" in s:
            section = "off"
        elif section is None:
            continue
        m = re.search(r"brake-on\s+at\s+t=\s*([\d.]+)\s*s,\s*v=\s*([\d.]+)", s)
        if m:
            out[f"{section}_brake_t"] = float(m.group(1))
            out[f"{section}_brake_v"] = float(m.group(2))
        m = re.search(r"stopped\s+at\s+t=\s*([\d.]+)\s*s\s+Δt=\s*([\d.]+)\s*s\s+distance=\s*([\d.]+)", s)
        if m:
            out[f"{section}_stop_t"]    = float(m.group(2))
            out[f"{section}_stop_dist"] = float(m.group(3))
            out[f"{section}_stopped"]   = True
        m = re.search(r"did NOT stop within scenario.\s+Final speed:\s+([\d.]+)", s)
        if m:
            out[f"{section}_final_v"] = float(m.group(1))
        m = re.match(r"(FL|FR|RL|RR):\s+peak=\s*([\d.]+)\s+mean=\s*([\d.]+)\s+locked=\s*([\d.]+)%", s)
        if m:
            wheel = m.group(1).lower()
            out[f"{section}_{wheel}_peak"]   = float(m.group(2))
            out[f"{section}_{wheel}_mean"]   = float(m.group(3))
            out[f"{section}_{wheel}_locked"] = float(m.group(4))
        m = re.search(r"ABS phase transitions:\s+FL=(\d+)\s+FR=(\d+)", s)
        if m:
            out[f"{section}_fl_events"] = int(m.group(1))
            out[f"{section}_fr_events"] = int(m.group(2))
        m = re.search(r"yaw drift over brake event:\s+([+\-\d.]+)°", s)
        if m:
            out[f"{section}_yaw_drift_deg"] = float(m.group(1))
    return out


# ---------------------------------------------------------------------------
# CSV loading
# ---------------------------------------------------------------------------

def load_csv(path: Path) -> list[dict]:
    rows: list[dict] = []
    with path.open() as f:
        for r in csv.DictReader(f):
            try:
                rows.append({k: float(v) for k, v in r.items()})
            except ValueError:
                rows.append(r)
    return rows


def find_brake_indices(rows: list[dict]) -> tuple[int, int]:
    """Return (brake_on_idx, brake_off_idx) in rows.  -1 if not found."""
    on_idx, off_idx = -1, -1
    for i, r in enumerate(rows):
        fb = r.get("applied_front_brake", 0)
        if on_idx < 0 and fb > 0.5:
            on_idx = i
        elif on_idx >= 0 and off_idx < 0 and fb < 0.5:
            off_idx = i
    if off_idx < 0:
        off_idx = len(rows) - 1
    return on_idx, off_idx


def find_btcm_brake_indices(rows: list[dict]) -> tuple[int, int]:
    """Same idea, but on the BTCM CSV — uses brake_pin field."""
    on_idx, off_idx = -1, -1
    for i, r in enumerate(rows):
        bp = r.get("brake_pin", 0)
        if on_idx < 0 and bp >= 0.5:
            on_idx = i
        elif on_idx >= 0 and off_idx < 0 and bp < 0.5:
            off_idx = i
    if off_idx < 0:
        off_idx = len(rows) - 1
    return on_idx, off_idx


# ---------------------------------------------------------------------------
# SVG primitives — hand-written, no matplotlib dependency
# ---------------------------------------------------------------------------

class Svg:
    """Minimal SVG builder with linear-axis line charts.

    Coordinates: caller passes data-space x/y; we map to pixel-space
    based on min/max, leaving a fixed-pixel margin for axes/labels.
    """

    def __init__(self, w: int = 720, h: int = 220, title: str = ""):
        self.w = w
        self.h = h
        self.title = title
        self.parts: list[str] = []
        self.parts.append(
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'viewBox="0 0 {w} {h}" width="{w}" height="{h}" '
            f'font-family="ui-monospace,Consolas,Menlo,monospace" '
            f'font-size="11">')
        self.parts.append('<rect width="100%" height="100%" fill="#ffffff"/>')
        if title:
            self.parts.append(
                f'<text x="{w/2}" y="14" text-anchor="middle" '
                f'font-size="12" font-weight="bold">{escape(title)}</text>')

    def axes(self,
             x_min: float, x_max: float,
             y_min: float, y_max: float,
             x_label: str = "", y_label: str = "",
             margin_l: int = 56, margin_r: int = 12,
             margin_t: int = 24, margin_b: int = 36) -> dict:
        """Draw axis box + ticks.  Returns a `to_px` dict for plotting."""
        plot_x0 = margin_l
        plot_y0 = margin_t
        plot_w  = self.w - margin_l - margin_r
        plot_h  = self.h - margin_t - margin_b

        if x_max <= x_min:
            x_max = x_min + 1.0
        if y_max <= y_min:
            y_max = y_min + 1.0

        # Axis frame.
        self.parts.append(
            f'<rect x="{plot_x0}" y="{plot_y0}" width="{plot_w}" '
            f'height="{plot_h}" fill="none" stroke="#444" stroke-width="0.5"/>')

        # X ticks (5).
        for i in range(6):
            xv = x_min + (x_max - x_min) * i / 5
            xp = plot_x0 + plot_w * i / 5
            self.parts.append(
                f'<line x1="{xp:.1f}" y1="{plot_y0+plot_h}" '
                f'x2="{xp:.1f}" y2="{plot_y0+plot_h+3}" stroke="#444"/>')
            self.parts.append(
                f'<text x="{xp:.1f}" y="{plot_y0+plot_h+14}" '
                f'text-anchor="middle" fill="#333">{xv:.2f}</text>')
        # Y ticks (5).
        for i in range(6):
            yv = y_min + (y_max - y_min) * i / 5
            yp = plot_y0 + plot_h - plot_h * i / 5
            self.parts.append(
                f'<line x1="{plot_x0-3}" y1="{yp:.1f}" '
                f'x2="{plot_x0}" y2="{yp:.1f}" stroke="#444"/>')
            self.parts.append(
                f'<text x="{plot_x0-5}" y="{yp:.1f}" '
                f'text-anchor="end" dominant-baseline="middle" '
                f'fill="#333">{yv:.2f}</text>')
        if x_label:
            self.parts.append(
                f'<text x="{plot_x0+plot_w/2}" y="{self.h-6}" '
                f'text-anchor="middle" fill="#333">{escape(x_label)}</text>')
        if y_label:
            self.parts.append(
                f'<text transform="translate(14,{plot_y0+plot_h/2}) rotate(-90)" '
                f'text-anchor="middle" fill="#333">{escape(y_label)}</text>')

        return {
            "x0": plot_x0, "y0": plot_y0,
            "w":  plot_w,  "h":  plot_h,
            "x_min": x_min, "x_max": x_max,
            "y_min": y_min, "y_max": y_max,
        }

    @staticmethod
    def to_px(ax: dict, x: float, y: float) -> tuple[float, float]:
        u = (x - ax["x_min"]) / (ax["x_max"] - ax["x_min"])
        v = (y - ax["y_min"]) / (ax["y_max"] - ax["y_min"])
        return ax["x0"] + ax["w"] * u, ax["y0"] + ax["h"] * (1 - v)

    def polyline(self, ax: dict, points: list[tuple[float, float]],
                 color: str, width: float = 1.2,
                 dash: Optional[str] = None) -> None:
        if not points:
            return
        pts = [self.to_px(ax, x, y) for x, y in points]
        d = " ".join(f"{x:.1f},{y:.1f}" for x, y in pts)
        dash_attr = f' stroke-dasharray="{dash}"' if dash else ""
        self.parts.append(
            f'<polyline fill="none" stroke="{color}" stroke-width="{width}" '
            f'points="{d}"{dash_attr}/>')

    def hline(self, ax: dict, y: float, color: str = "#999",
              dash: str = "3 3", label: str = "") -> None:
        x0, _ = self.to_px(ax, ax["x_min"], y)
        x1, yp = self.to_px(ax, ax["x_max"], y)
        self.parts.append(
            f'<line x1="{x0:.1f}" y1="{yp:.1f}" x2="{x1:.1f}" y2="{yp:.1f}" '
            f'stroke="{color}" stroke-width="0.7" stroke-dasharray="{dash}"/>')
        if label:
            self.parts.append(
                f'<text x="{x1-2:.1f}" y="{yp-2:.1f}" text-anchor="end" '
                f'fill="{color}">{escape(label)}</text>')

    def vline(self, ax: dict, x: float, color: str = "#888",
              dash: str = "2 3", label: str = "") -> None:
        xp, y0 = self.to_px(ax, x, ax["y_max"])
        _,  y1 = self.to_px(ax, x, ax["y_min"])
        self.parts.append(
            f'<line x1="{xp:.1f}" y1="{y0:.1f}" x2="{xp:.1f}" y2="{y1:.1f}" '
            f'stroke="{color}" stroke-width="0.7" stroke-dasharray="{dash}"/>')
        if label:
            self.parts.append(
                f'<text x="{xp+3:.1f}" y="{y0+10:.1f}" fill="{color}">'
                f'{escape(label)}</text>')

    def legend(self, ax: dict, items: list[tuple[str, str]]) -> None:
        x = ax["x0"] + 8
        y = ax["y0"] + 12
        for label, color in items:
            self.parts.append(
                f'<rect x="{x}" y="{y-7}" width="10" height="3" fill="{color}"/>')
            self.parts.append(
                f'<text x="{x+14}" y="{y-1}" fill="#222">'
                f'{escape(label)}</text>')
            y += 13

    def phase_band(self, ax: dict, t_pairs: list[tuple[float, float, int]],
                   y_band_top: float, band_height_px: int = 14,
                   label: str = "") -> None:
        """Render an ABS-phase Gantt band.

        t_pairs: (t_start, t_end, phase) — phase 0=APPLY, 1=HOLD, 2=DUMP, -1=stale.
        y_band_top: data-space y-coordinate for the top of the band.
        """
        colors = {0: "#9bda9b", 1: "#ffd66e", 2: "#f08a8a", -1: "#dddddd"}
        # Convert y_band_top to pixel and grow downward.
        x0, yp_top = self.to_px(ax, ax["x_min"], y_band_top)
        for t0, t1, ph in t_pairs:
            xa, _ = self.to_px(ax, t0, y_band_top)
            xb, _ = self.to_px(ax, t1, y_band_top)
            xa = max(xa, ax["x0"])
            xb = min(xb, ax["x0"] + ax["w"])
            if xb <= xa:
                continue
            self.parts.append(
                f'<rect x="{xa:.1f}" y="{yp_top:.1f}" '
                f'width="{xb-xa:.1f}" height="{band_height_px}" '
                f'fill="{colors.get(ph, "#ccc")}" stroke="#444" '
                f'stroke-width="0.3"/>')
        if label:
            self.parts.append(
                f'<text x="{ax["x0"]+ax["w"]+4}" y="{yp_top+band_height_px-3}" '
                f'fill="#333">{escape(label)}</text>')

    def render(self) -> str:
        self.parts.append("</svg>")
        return "\n".join(self.parts) + "\n"


def escape(s: str) -> str:
    return (s.replace("&", "&amp;")
             .replace("<", "&lt;")
             .replace(">", "&gt;"))


# ---------------------------------------------------------------------------
# Chart builders — one per visualization
# ---------------------------------------------------------------------------

def chart_speed_compare(on_rows: list[dict], off_rows: list[dict],
                         on_brake: int, on_end: int,
                         off_brake: int, off_end: int,
                         title: str) -> str:
    """Vehicle-speed comparison — BTCM-on overlaid on BTCM-off."""
    svg = Svg(w=720, h=220, title=title)

    on_pts  = [(r["sim_time_s"], r["speed_mps"])
               for r in on_rows[on_brake:on_end+1]]   if on_brake  >= 0 else []
    off_pts = [(r["sim_time_s"], r["speed_mps"])
               for r in off_rows[off_brake:off_end+1]] if off_brake >= 0 else []
    if not on_pts and not off_pts:
        svg.axes(0, 1, 0, 1, "t [s]", "v [m/s]")
        return svg.render()

    xs = [p[0] for p in on_pts] + [p[0] for p in off_pts]
    ys = [p[1] for p in on_pts] + [p[1] for p in off_pts]
    ax = svg.axes(min(xs), max(xs), 0, max(ys) * 1.05,
                  x_label="t [s]", y_label="v [m/s]")
    svg.polyline(ax, off_pts, color="#e08a3c", width=1.4)
    svg.polyline(ax, on_pts,  color="#3470c0", width=1.4)
    svg.legend(ax, [("BTCM-on", "#3470c0"), ("BTCM-off", "#e08a3c")])
    return svg.render()


def chart_per_wheel_speed(rows: list[dict], brake_idx: int, end_idx: int,
                          title: str) -> str:
    """Per-wheel ground speed (omega × radius) plus chassis speed."""
    svg = Svg(w=720, h=240, title=title)
    if brake_idx < 0:
        svg.axes(0, 1, 0, 1, "t [s]", "m/s")
        return svg.render()
    sub = rows[brake_idx:end_idx+1]
    chassis  = [(r["sim_time_s"], r["speed_mps"])              for r in sub]
    wheel_fl = [(r["sim_time_s"], abs(r["wheel_omega_fl"]) * TIRE_RADIUS_M) for r in sub]
    wheel_fr = [(r["sim_time_s"], abs(r["wheel_omega_fr"]) * TIRE_RADIUS_M) for r in sub]
    wheel_rl = [(r["sim_time_s"], abs(r["wheel_omega_rl"]) * TIRE_RADIUS_M) for r in sub]
    wheel_rr = [(r["sim_time_s"], abs(r["wheel_omega_rr"]) * TIRE_RADIUS_M) for r in sub]
    xs = [p[0] for p in chassis]
    ys = ([p[1] for p in chassis]
          + [p[1] for p in wheel_fl]
          + [p[1] for p in wheel_fr]
          + [p[1] for p in wheel_rl]
          + [p[1] for p in wheel_rr])
    ax = svg.axes(min(xs), max(xs), 0, max(ys) * 1.05,
                  x_label="t [s]", y_label="m/s")
    svg.polyline(ax, chassis,  color="#000", width=1.6)
    svg.polyline(ax, wheel_fl, color="#c0392b", width=1.0)
    svg.polyline(ax, wheel_fr, color="#27ae60", width=1.0)
    svg.polyline(ax, wheel_rl, color="#2980b9", width=1.0)
    svg.polyline(ax, wheel_rr, color="#8e44ad", width=1.0)
    svg.legend(ax, [
        ("chassis",  "#000"),
        ("FL wheel", "#c0392b"),
        ("FR wheel", "#27ae60"),
        ("RL wheel", "#2980b9"),
        ("RR wheel", "#8e44ad"),
    ])
    return svg.render()


def chart_slip_ratios(rows: list[dict], brake_idx: int, end_idx: int,
                      title: str) -> str:
    svg = Svg(w=720, h=220, title=title)
    if brake_idx < 0:
        svg.axes(0, 1, 0, 1, "t [s]", "slip")
        return svg.render()
    sub = rows[brake_idx:end_idx+1]
    fl = [(r["sim_time_s"], r["slip_ratio_fl"]) for r in sub]
    fr = [(r["sim_time_s"], r["slip_ratio_fr"]) for r in sub]
    rl = [(r["sim_time_s"], r["slip_ratio_rl"]) for r in sub]
    rr = [(r["sim_time_s"], r["slip_ratio_rr"]) for r in sub]
    xs = [p[0] for p in fl]
    ax = svg.axes(min(xs), max(xs), 0, 1.05,
                  x_label="t [s]", y_label="slip ratio")
    svg.hline(ax, 0.15, color="#888", label="enter (0.15)")
    svg.hline(ax, 0.05, color="#888", label="exit (0.05)")
    svg.polyline(ax, fl, color="#c0392b", width=1.0)
    svg.polyline(ax, fr, color="#27ae60", width=1.0)
    svg.polyline(ax, rl, color="#2980b9", width=1.0)
    svg.polyline(ax, rr, color="#8e44ad", width=1.0)
    svg.legend(ax, [
        ("FL", "#c0392b"),
        ("FR", "#27ae60"),
        ("RL", "#2980b9"),
        ("RR", "#8e44ad"),
    ])
    return svg.render()


def phase_segments(rows: list[dict], col: str,
                   start_idx: int, end_idx: int) -> list[tuple[float, float, int]]:
    """Compress consecutive same-phase samples into (t_start, t_end, phase)."""
    segs: list[tuple[float, float, int]] = []
    if start_idx < 0:
        return segs
    cur_phase = int(rows[start_idx].get(col, -1))
    seg_start = rows[start_idx]["sim_time_s"]
    for i in range(start_idx + 1, end_idx + 1):
        ph = int(rows[i].get(col, -1))
        if ph != cur_phase:
            segs.append((seg_start, rows[i]["sim_time_s"], cur_phase))
            seg_start = rows[i]["sim_time_s"]
            cur_phase = ph
    segs.append((seg_start, rows[end_idx]["sim_time_s"], cur_phase))
    return segs


def chart_abs_phase_timeline(rows: list[dict], brake_idx: int, end_idx: int,
                              title: str) -> str:
    """Two-band Gantt: FL on top, FR below.  Below them a per-segment count
    summary of how many APPLY/HOLD/DUMP transitions happened."""
    svg = Svg(w=720, h=180, title=title)
    if brake_idx < 0:
        svg.axes(0, 1, 0, 1, "t [s]", "")
        return svg.render()
    t_min = rows[brake_idx]["sim_time_s"]
    t_max = rows[end_idx]["sim_time_s"]
    ax = svg.axes(t_min, t_max, 0, 1, x_label="t [s]", y_label="")

    # Band y-position chosen in data space then mapped.
    fl_segs = phase_segments(rows, "abs_phase_fl", brake_idx, end_idx)
    fr_segs = phase_segments(rows, "abs_phase_fr", brake_idx, end_idx)
    svg.phase_band(ax, fl_segs, y_band_top=0.85, label="FL")
    svg.phase_band(ax, fr_segs, y_band_top=0.55, label="FR")

    # Legend.
    svg.parts.append(
        f'<rect x="{ax["x0"]+8}" y="{ax["y0"]+5}" width="10" height="8" '
        f'fill="#9bda9b" stroke="#444" stroke-width="0.3"/>')
    svg.parts.append(
        f'<text x="{ax["x0"]+22}" y="{ax["y0"]+12}" fill="#222">APPLY</text>')
    svg.parts.append(
        f'<rect x="{ax["x0"]+72}" y="{ax["y0"]+5}" width="10" height="8" '
        f'fill="#ffd66e" stroke="#444" stroke-width="0.3"/>')
    svg.parts.append(
        f'<text x="{ax["x0"]+86}" y="{ax["y0"]+12}" fill="#222">HOLD</text>')
    svg.parts.append(
        f'<rect x="{ax["x0"]+128}" y="{ax["y0"]+5}" width="10" height="8" '
        f'fill="#f08a8a" stroke="#444" stroke-width="0.3"/>')
    svg.parts.append(
        f'<text x="{ax["x0"]+142}" y="{ax["y0"]+12}" fill="#222">DUMP</text>')
    svg.parts.append(
        f'<rect x="{ax["x0"]+184}" y="{ax["y0"]+5}" width="10" height="8" '
        f'fill="#dddddd" stroke="#444" stroke-width="0.3"/>')
    svg.parts.append(
        f'<text x="{ax["x0"]+198}" y="{ax["y0"]+12}" fill="#222">stale</text>')

    return svg.render()


def chart_rear_modulation(rows: list[dict], brake_idx: int, end_idx: int,
                            title: str) -> str:
    """Rear axle ABS modulation, shown as the actual EMB motor command.

    Unlike the front axle (discrete APPLY/HOLD/DUMP solenoid phases),
    the rear EMB has a continuous motor-current command in [-1, +1]:
        +1 = full apply (motor pushing the shoes outward)
         0 = idle / hold position
        -1 = full release (motor retracting the shoes)
    The btcm_rear module translates the same ABS phase decisions the
    front axle uses into this signed command, so this chart shows
    "what the BTCM is telling the rear axle to do" — the analog of
    the front phase Gantt.
    """
    svg = Svg(w=720, h=220, title=title)
    if brake_idx < 0:
        svg.axes(0, 1, -1.1, 1.1, "t [s]", "EMB cmd")
        return svg.render()
    sub = rows[brake_idx:end_idx+1]
    lr = [(r["sim_time_s"], r["emb_cmd_lr"]) for r in sub]
    rr = [(r["sim_time_s"], r["emb_cmd_rr"]) for r in sub]
    xs = [p[0] for p in lr]
    ax = svg.axes(min(xs), max(xs), -1.1, 1.1,
                  x_label="t [s]", y_label="EMB cmd [-1..+1]")
    svg.hline(ax, 0, color="#aaa", dash="1 0")
    svg.hline(ax, 0.05,  color="#9bda9b", label="apply deadband")
    svg.hline(ax, -0.05, color="#f08a8a", label="release deadband")
    svg.polyline(ax, lr, color="#2980b9", width=1.2)
    svg.polyline(ax, rr, color="#8e44ad", width=1.2)
    svg.legend(ax, [
        ("RL motor cmd", "#2980b9"),
        ("RR motor cmd", "#8e44ad"),
    ])
    return svg.render()


def chart_brake_outputs(on_rows: list[dict], off_rows: list[dict],
                         on_brake: int, on_end: int,
                         off_brake: int, off_end: int,
                         title: str) -> str:
    """Effective per-axle brake force ratio applied to Chrono.

    Front: applied_front_brake field directly — that's the post-ABS
    ratio fed to the Chrono caliper after the host modulator's
    finite-rate τ model.

    Rear: derived from emb_cmd_*.  We *cannot* use applied_rear_brake
    directly because that field stores the *symmetric* command (the
    driver pedal, ≈ 1.0 throughout the brake event) rather than the
    per-wheel override that ApplyRearEmbBrake feeds into Chrono via
    ApplyRearBrakePerWheel().  For each rear wheel, the effective
    apply-force ratio is max(0, emb_cmd) — positive cmd = apply,
    negative cmd = motor releasing the shoes (no brake force), 0 =
    hold position (also no incremental force).  We average LR and RR
    here for a single per-axle line.

    BTCM-off path: rear ratio is forced to 0 (the EV1's rear EMB
    has no hydraulic backup — when BTCM is stale the host's
    ApplyRearEmbBrake passes 0/0 to Chrono regardless of pedal).
    """
    svg = Svg(w=720, h=240, title=title)

    def rear_eff(rows: list[dict], a: int, b: int,
                 zero_when_btcm_off: bool) -> list[tuple[float, float]]:
        out: list[tuple[float, float]] = []
        if a < 0:
            return out
        for r in rows[a:b+1]:
            if zero_when_btcm_off:
                out.append((r["sim_time_s"], 0.0))
                continue
            lr = max(0.0, r.get("emb_cmd_lr", 0.0))
            rr = max(0.0, r.get("emb_cmd_rr", 0.0))
            out.append((r["sim_time_s"], 0.5 * (lr + rr)))
        return out

    on_pts_f = [(r["sim_time_s"], r["applied_front_brake"])
                for r in on_rows[on_brake:on_end+1]] if on_brake >= 0 else []
    on_pts_r = rear_eff(on_rows, on_brake, on_end, zero_when_btcm_off=False)
    off_pts_f = [(r["sim_time_s"], r["applied_front_brake"])
                 for r in off_rows[off_brake:off_end+1]] if off_brake >= 0 else []
    off_pts_r = rear_eff(off_rows, off_brake, off_end, zero_when_btcm_off=True)

    if not on_pts_f and not off_pts_f:
        svg.axes(0, 1, 0, 1, "t [s]", "brake ratio")
        return svg.render()
    xs = [p[0] for p in on_pts_f] + [p[0] for p in off_pts_f]
    ax = svg.axes(min(xs), max(xs), 0, 1.1,
                  x_label="t [s]", y_label="effective brake ratio [0..1]")
    svg.polyline(ax, off_pts_r, color="#e08a3c", width=1.2, dash="3 3")
    svg.polyline(ax, off_pts_f, color="#e08a3c", width=1.4)
    svg.polyline(ax, on_pts_r,  color="#3470c0", width=1.2, dash="3 3")
    svg.polyline(ax, on_pts_f,  color="#3470c0", width=1.4)
    svg.legend(ax, [
        ("BTCM-on  front (caliper)",  "#3470c0"),
        ("BTCM-on  rear  (EMB apply force)",  "#3470c0"),
        ("BTCM-off front (caliper)",  "#e08a3c"),
        ("BTCM-off rear  (forced to 0)", "#e08a3c"),
    ])
    return svg.render()


def chart_actuator_lag(rows: list[dict], brake_idx: int, end_idx: int,
                        title: str) -> str:
    """Show the modeled hardware lag between command and actuator.

    Plots applied_front_brake (command sent to Chrono), the modeled
    front_brake_pressure (caliper pressure after τ ≈ 50/80 ms first-
    order lag), the applied_rear_brake (rear command), and
    rear_brake_position (drum shoe position after rate-limited
    actuator at ~3.33/s — full stroke ~300 ms).
    """
    svg = Svg(w=720, h=220, title=title)
    if brake_idx < 0:
        svg.axes(0, 1, 0, 1, "t [s]", "ratio")
        return svg.render()
    sub = rows[brake_idx:end_idx+1]
    cmd_f  = [(r["sim_time_s"], r["applied_front_brake"])  for r in sub]
    pres_f = [(r["sim_time_s"], r.get("front_brake_pressure", 0)) for r in sub]
    cmd_r  = [(r["sim_time_s"], r["applied_rear_brake"])   for r in sub]
    pos_r  = [(r["sim_time_s"], r.get("rear_brake_position", 0)) for r in sub]
    xs = [p[0] for p in cmd_f]
    ax = svg.axes(min(xs), max(xs), 0, 1.1,
                  x_label="t [s]", y_label="ratio [0..1]")
    svg.polyline(ax, cmd_f,  color="#3470c0", width=1.4)
    svg.polyline(ax, pres_f, color="#3470c0", width=1.0, dash="2 3")
    svg.polyline(ax, cmd_r,  color="#c0392b", width=1.4)
    svg.polyline(ax, pos_r,  color="#c0392b", width=1.0, dash="2 3")
    svg.legend(ax, [
        ("front cmd",         "#3470c0"),
        ("front caliper (post-τ ≈ 50 ms)", "#3470c0"),  # dashed
        ("rear cmd",          "#c0392b"),
        ("rear shoe (post-rate-limit)",     "#c0392b"),  # dashed
    ])
    return svg.render()


def chart_btcm_internal_view(btcm_rows: list[dict],
                              chassis_rows: list[dict],
                              title: str) -> str:
    """The BTCM firmware's *own* perception of the brake event.

    Plots the firmware-side `vehicle_speed_mps` (the algorithm's
    reference speed estimate) and the four per-wheel ground-speed
    readings derived from tone-ring counts (`wheel_speed_rps × tire
    radius`).  All BTCM-side data is aligned to the BTCM's own brake-
    on event (where brake_pin first goes high) so t=0 here corresponds
    to t=0 in the chassis-view charts above (which use the chassis-
    side brake-on as their reference).  Real wall-clock time has a
    ~1 s offset between ev1sim and BTCM startup that we don't try to
    surface.

    Useful for spotting where the firmware's view diverges from
    reality: vehicle_speed_mps may stick high when ABS over-modulates
    (max-wheel-based estimator with no accelerometer), or wheel-speed
    quantization at the firmware's 50 ms tone-ring window can show
    up as a stair-step compared to the smoother chassis truth.
    """
    svg = Svg(w=720, h=260, title=title)
    btcm_on, btcm_off = find_btcm_brake_indices(btcm_rows)
    if btcm_on < 0 or not btcm_rows:
        svg.axes(0, 1, 0, 1, "t since brake-on [s]", "m/s")
        return svg.render()
    t0 = btcm_rows[btcm_on]["wall_t_s"]

    # Trim past the end of brake (off_idx)+ a little tail.
    end = min(btcm_off + 50, len(btcm_rows) - 1)
    sub = btcm_rows[btcm_on:end + 1]
    fw_v   = [(r["wall_t_s"] - t0, r["vehicle_speed_mps"])  for r in sub]
    fw_fl  = [(r["wall_t_s"] - t0, r["wheel_speed_fl"] * TIRE_RADIUS_M) for r in sub]
    fw_fr  = [(r["wall_t_s"] - t0, r["wheel_speed_fr"] * TIRE_RADIUS_M) for r in sub]
    fw_rl  = [(r["wall_t_s"] - t0, r["wheel_speed_rl"] * TIRE_RADIUS_M) for r in sub]
    fw_rr  = [(r["wall_t_s"] - t0, r["wheel_speed_rr"] * TIRE_RADIUS_M) for r in sub]

    # Overlay the chassis truth on the same time axis.  Chassis brake
    # event has its own indices.
    ch_on, ch_off = find_brake_indices(chassis_rows)
    chassis_pts: list[tuple[float, float]] = []
    if ch_on >= 0:
        c0 = chassis_rows[ch_on]["sim_time_s"]
        end_c = min(ch_off + 50, len(chassis_rows) - 1)
        chassis_pts = [(r["sim_time_s"] - c0, r["speed_mps"])
                       for r in chassis_rows[ch_on:end_c + 1]]

    xs = [p[0] for p in fw_v] + [p[0] for p in chassis_pts]
    ys = ([p[1] for p in fw_v]
          + [p[1] for p in chassis_pts]
          + [p[1] for p in fw_fl]
          + [p[1] for p in fw_fr]
          + [p[1] for p in fw_rl]
          + [p[1] for p in fw_rr])
    if not xs or not ys:
        svg.axes(0, 1, 0, 1, "t since brake-on [s]", "m/s")
        return svg.render()
    ax = svg.axes(min(xs), max(xs), 0, max(ys) * 1.05,
                  x_label="t since brake-on [s]", y_label="m/s")
    svg.polyline(ax, chassis_pts, color="#000", width=1.6)
    svg.polyline(ax, fw_v,  color="#3470c0", width=1.6)
    svg.polyline(ax, fw_fl, color="#c0392b", width=1.0)
    svg.polyline(ax, fw_fr, color="#27ae60", width=1.0)
    svg.polyline(ax, fw_rl, color="#2980b9", width=1.0, dash="3 3")
    svg.polyline(ax, fw_rr, color="#8e44ad", width=1.0, dash="3 3")
    svg.legend(ax, [
        ("chassis truth (ev1sim)",        "#000"),
        ("firmware vehicle_speed_mps",    "#3470c0"),
        ("firmware FL ground-speed",      "#c0392b"),
        ("firmware FR ground-speed",      "#27ae60"),
        ("firmware RL ground-speed",      "#2980b9"),
        ("firmware RR ground-speed",      "#8e44ad"),
    ])
    return svg.render()


def chart_btcm_accel(btcm_rows: list[dict], title: str) -> str:
    """Accelerometer reading the BTCM firmware sees vs. zero line.

    Even when the algorithm doesn't consume it (build-time gated by
    BTCM_USE_ACCELEROMETER), the host bridge still publishes accel
    so we can see what a future-gen ABS would have available.
    """
    svg = Svg(w=720, h=180, title=title)
    btcm_on, btcm_off = find_btcm_brake_indices(btcm_rows)
    if btcm_on < 0 or not btcm_rows:
        svg.axes(0, 1, -1, 1, "t since brake-on [s]", "accel [m/s²]")
        return svg.render()
    t0 = btcm_rows[btcm_on]["wall_t_s"]
    end = min(btcm_off + 50, len(btcm_rows) - 1)
    sub = btcm_rows[btcm_on:end + 1]
    pts = [(r["wall_t_s"] - t0, r["longit_accel_mps2"]) for r in sub]
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    if not pts:
        svg.axes(0, 1, -1, 1, "t since brake-on [s]", "accel [m/s²]")
        return svg.render()
    y_max = max(0.5, max(abs(min(ys)), abs(max(ys))) * 1.15)
    ax = svg.axes(min(xs), max(xs), -y_max, y_max,
                  x_label="t since brake-on [s]", y_label="longit accel [m/s²]")
    svg.hline(ax, 0, color="#666", dash="1 0")
    svg.polyline(ax, pts, color="#3470c0", width=1.2)
    return svg.render()


# ---------------------------------------------------------------------------
# Animated HTML replay — top-down view with scrubbable timeline
# ---------------------------------------------------------------------------

# Map test name → level JSON path so the replay can render surface
# patches as a colored background (asphalt grey, ice light blue).
LEVEL_FILES = {
    "high_mu":  "level/flat_asphalt.json",
    "low_mu":   "level/flat_ice.json",
    "mu_jump":  "level/flat_ice_transition.json",
    "split_mu": "level/flat_split_mu.json",
}


def make_replay_html(t: str,
                     on_rows: list[dict],
                     off_rows: list[dict],
                     level_path) -> str:
    """Self-contained HTML+SVG+JS top-down replay of a scenario.

    Top-down view of the chassis with surface patches, car body
    (rotated by yaw_deg), wheels colored by slip, position trail,
    play / pause / scrub controls, and a BTCM-on/off run toggle.
    No external resources — opens cleanly with file:// URLs.
    """
    import json

    def frames_from(rows: list[dict]) -> list[dict]:
        out = []
        prev_t = -1.0
        for r in rows:
            t_s = r["sim_time_s"]
            if t_s - prev_t < 0.04:  # decimate to ~25 fps
                continue
            prev_t = t_s
            out.append({
                "t":   round(t_s, 3),
                "x":   round(r["pos_x"], 3),
                "y":   round(r["pos_y"], 3),
                "yaw": round(r.get("yaw_deg", 0.0), 2),
                "v":   round(r["speed_mps"], 2),
                "fb":  round(r["applied_front_brake"], 2),
                "rb":  round(r["applied_rear_brake"], 2),
                "sl":  [round(r[f"slip_ratio_{w}"], 3) for w in ("fl","fr","rl","rr")],
                "ph":  [int(r.get(f"abs_phase_{w}", -1)) for w in ("fl","fr")],
                "emb": [round(r.get(f"emb_cmd_{w}", 0.0), 2) for w in ("lr","rr")],
            })
        return out

    on_frames  = frames_from(on_rows)
    off_frames = frames_from(off_rows)
    all_x = [f["x"] for f in (on_frames + off_frames)]
    all_y = [f["y"] for f in (on_frames + off_frames)]
    if not all_x:
        return "<html><body>No data.</body></html>"
    x_min, x_max = min(all_x) - 5, max(all_x) + 5
    y_min, y_max = min(all_y) - 5, max(all_y) + 5
    y_pad = max(3.0, (y_max - y_min) * 0.5)
    y_min -= y_pad
    y_max += y_pad

    patches: list[dict] = []
    if level_path and Path(level_path).exists():
        try:
            level = json.loads(Path(level_path).read_text())
            for p in level.get("patches", []):
                if p.get("type") != "plane":
                    continue
                cx, cy, _ = p.get("center", [0, 0, 0])
                w, h = p.get("size", [0, 0])
                patches.append({
                    "cx": cx, "cy": cy, "w": w, "h": h,
                    "surface": p.get("surface", "unknown"),
                    "friction": p.get("friction", 0.5),
                })
        except Exception:
            pass

    # If no level file (high_mu and low_mu use a rigid_plane in the
    # config rather than a level), synthesize a single patch covering
    # the full traveled extent so the replay still shows surface
    # context.  Friction and surface name from the test ID.
    if not patches:
        single = {
            "high_mu":  {"surface": "asphalt", "friction": 0.9},
            "low_mu":   {"surface": "ice",     "friction": 0.10},
            "mu_jump":  {"surface": "asphalt", "friction": 0.9},
            "split_mu": {"surface": "asphalt", "friction": 0.9},
        }.get(t, {"surface": "asphalt", "friction": 0.9})
        patches.append({
            "cx": (x_min + x_max) / 2,
            "cy": (y_min + y_max) / 2,
            "w":  x_max - x_min,
            "h":  y_max - y_min,
            "surface":  single["surface"],
            "friction": single["friction"],
        })

    payload = {
        "test":       t,
        "x_min":      x_min,
        "x_max":      x_max,
        "y_min":      y_min,
        "y_max":      y_max,
        "patches":    patches,
        "on_frames":  on_frames,
        "off_frames": off_frames,
    }
    payload_json = json.dumps(payload)

    html = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>__TEST__ — top-down replay</title>
<style>
body { margin:0; padding:16px; font-family:ui-monospace,Consolas,Menlo,monospace;
       background:#f6f7f8; color:#222; }
h1 { font-size:16px; margin:0 0 8px 0; }
#scene { background:#fff; border:1px solid #999; }
#hud { font-size:12px; line-height:1.5; margin-top:8px; white-space:pre; }
.controls { display:flex; gap:8px; align-items:center; margin:8px 0; flex-wrap:wrap; }
button, label { font-family:inherit; font-size:12px; }
button { padding:4px 10px; cursor:pointer; }
input[type=range] { flex:1; min-width:300px; }
select { font-family:inherit; font-size:12px; padding:2px 4px; }
.legend { font-size:11px; color:#555; margin-top:4px; }
.legend span { display:inline-block; padding:0 8px; }
.legend .dot { display:inline-block; width:10px; height:10px; border-radius:50%;
               vertical-align:middle; margin-right:4px; border:1px solid #444; }
</style></head><body>
<h1>__TEST__ — top-down replay (<span id="run-label">BTCM-on</span>)</h1>
<svg id="scene" viewBox="0 0 980 320" width="980" height="320"></svg>
<div class="controls">
  <button id="play">▶ play</button>
  <button id="step-back">«</button>
  <button id="step-fwd">»</button>
  <input type="range" id="scrub" min="0" max="100" value="0" step="1">
  <span id="time-label">t = 0.00 s</span>
  <label>speed
    <select id="speed">
      <option value="0.25">0.25×</option><option value="0.5">0.5×</option>
      <option value="1" selected>1×</option><option value="2">2×</option>
      <option value="4">4×</option>
    </select></label>
  <label>run
    <select id="which-run">
      <option value="on" selected>BTCM-on</option>
      <option value="off">BTCM-off</option>
    </select></label>
</div>
<div class="legend">
  <span><span class="dot" style="background:#9bda9b"></span>rolling clean</span>
  <span><span class="dot" style="background:#ffd66e"></span>mid-slip (peak grip)</span>
  <span><span class="dot" style="background:#f08a8a"></span>locked / heavy slip</span>
  <span><span class="dot" style="background:#7fb6ff"></span>spinning (negative slip)</span>
  <span><span class="dot" style="background:#bbb"></span>asphalt</span>
  <span><span class="dot" style="background:#cfe6ff"></span>ice</span>
</div>
<div id="hud"></div>
<script>
const DATA = __PAYLOAD__;
const svg = document.getElementById("scene");
const hud = document.getElementById("hud");
const scrub = document.getElementById("scrub");
const playBtn = document.getElementById("play");
const timeLabel = document.getElementById("time-label");
const runLabel = document.getElementById("run-label");
const speedSel = document.getElementById("speed");
const runSel = document.getElementById("which-run");
const stepBack = document.getElementById("step-back");
const stepFwd  = document.getElementById("step-fwd");
const VIEW_W=980, VIEW_H=320;
const carLengthM=4.31, carWidthM=1.76, wheelbaseM=2.51, trackM=1.50;
function worldX(x){return((x-DATA.x_min)/(DATA.x_max-DATA.x_min))*VIEW_W;}
function worldY(y){return VIEW_H-((y-DATA.y_min)/(DATA.y_max-DATA.y_min))*VIEW_H;}
const sx=VIEW_W/(DATA.x_max-DATA.x_min), sy=VIEW_H/(DATA.y_max-DATA.y_min);
function meterPxX(m){return m*sx;} function meterPxY(m){return m*sy;}
function drawSurfaces(){
  for(const p of DATA.patches){
    const x0=worldX(p.cx-p.w/2), x1=worldX(p.cx+p.w/2);
    const y0=worldY(p.cy+p.h/2), y1=worldY(p.cy-p.h/2);
    const r=document.createElementNS("http://www.w3.org/2000/svg","rect");
    r.setAttribute("x",Math.min(x0,x1));r.setAttribute("y",Math.min(y0,y1));
    r.setAttribute("width",Math.abs(x1-x0));r.setAttribute("height",Math.abs(y1-y0));
    let c="#fffbe0";
    if(p.surface==="asphalt")c="#bbb"; else if(p.surface==="ice")c="#cfe6ff";
    r.setAttribute("fill",c);r.setAttribute("stroke","#777");r.setAttribute("stroke-width","0.5");
    svg.appendChild(r);
    const tx=document.createElementNS("http://www.w3.org/2000/svg","text");
    tx.setAttribute("x",(Math.min(x0,x1)+Math.max(x0,x1))/2);
    tx.setAttribute("y",Math.min(y0,y1)+14);
    tx.setAttribute("font-size","10");tx.setAttribute("fill","#666");
    tx.setAttribute("text-anchor","middle");
    tx.textContent=p.surface+" μ="+p.friction.toFixed(2);
    svg.appendChild(tx);
  }
}
function slipColor(s){
  if(s<-0.05)return"#7fb6ff";
  if(s<0.05)return"#9bda9b";
  if(s<0.20)return"#ffd66e";
  return"#f08a8a";
}
let trailG=null;
function drawTrail(F,i){
  if(trailG)trailG.remove();
  trailG=document.createElementNS("http://www.w3.org/2000/svg","g");
  svg.appendChild(trailG);
  const tn=F[i].t, pts=[];
  for(let k=0;k<=i;++k){
    if(tn-F[k].t>3.0)continue;
    pts.push(worldX(F[k].x).toFixed(1)+","+worldY(F[k].y).toFixed(1));
  }
  const p=document.createElementNS("http://www.w3.org/2000/svg","polyline");
  p.setAttribute("fill","none");p.setAttribute("stroke","#3470c0");
  p.setAttribute("stroke-width","1.5");p.setAttribute("stroke-opacity","0.6");
  p.setAttribute("points",pts.join(" "));
  trailG.appendChild(p);
}
const carG=document.createElementNS("http://www.w3.org/2000/svg","g");
svg.appendChild(carG);
const bodyW=meterPxX(carLengthM), bodyH=meterPxY(carWidthM);
const body=document.createElementNS("http://www.w3.org/2000/svg","rect");
body.setAttribute("x",-bodyW/2);body.setAttribute("y",-bodyH/2);
body.setAttribute("width",bodyW);body.setAttribute("height",bodyH);
body.setAttribute("fill","#e8e8e8");body.setAttribute("stroke","#222");
body.setAttribute("stroke-width","1");body.setAttribute("rx",bodyH*0.15);
carG.appendChild(body);
const heading=document.createElementNS("http://www.w3.org/2000/svg","polygon");
heading.setAttribute("points",
  (bodyW*0.30)+",-"+(bodyH*0.20)+" "+
  (bodyW*0.45)+",0 "+
  (bodyW*0.30)+","+(bodyH*0.20));
heading.setAttribute("fill","#3470c0");carG.appendChild(heading);
const wheelOff=[
  {ix: meterPxX(wheelbaseM/2), iy:-meterPxY(trackM/2)},
  {ix: meterPxX(wheelbaseM/2), iy: meterPxY(trackM/2)},
  {ix:-meterPxX(wheelbaseM/2), iy:-meterPxY(trackM/2)},
  {ix:-meterPxX(wheelbaseM/2), iy: meterPxY(trackM/2)}];
const wheelEls=[];
for(let i=0;i<4;++i){
  const c=document.createElementNS("http://www.w3.org/2000/svg","circle");
  c.setAttribute("cx",wheelOff[i].ix);c.setAttribute("cy",wheelOff[i].iy);
  c.setAttribute("r",4);c.setAttribute("stroke","#222");c.setAttribute("stroke-width","0.6");
  carG.appendChild(c);wheelEls.push(c);
}
drawSurfaces();
let frames=DATA.on_frames, idx=0, playing=false, lastWall=0, speed=1.0;
function setRun(w){
  frames=(w==="on")?DATA.on_frames:DATA.off_frames;
  runLabel.textContent=(w==="on")?"BTCM-on":"BTCM-off";
  scrub.max=Math.max(0,frames.length-1);
  if(idx>=frames.length)idx=frames.length-1;
  redraw();
}
function redraw(){
  if(!frames.length)return;
  const f=frames[Math.min(Math.floor(idx),frames.length-1)];
  carG.setAttribute("transform",
    "translate("+worldX(f.x).toFixed(1)+","+worldY(f.y).toFixed(1)+")"+
    " rotate("+(-f.yaw).toFixed(2)+")");
  for(let i=0;i<4;++i)wheelEls[i].setAttribute("fill",slipColor(f.sl[i]));
  drawTrail(frames,Math.floor(idx));
  scrub.value=Math.floor(idx);
  timeLabel.textContent="t = "+f.t.toFixed(2)+" s";
  const W=["FL","FR","RL","RR"];
  let s="";
  s+="v = "+f.v.toFixed(2)+" m/s    ";
  s+="front cmd = "+f.fb.toFixed(2)+"    ";
  s+="rear cmd  = "+f.rb.toFixed(2)+"\\n";
  s+="slip:  ";
  for(let i=0;i<4;++i)s+=W[i]+" "+f.sl[i].toFixed(2)+"  ";
  s+="\\n";
  const pn=p=>p===0?"APPLY":p===1?"HOLD":p===2?"DUMP":"—";
  s+="ABS phase: FL "+pn(f.ph[0]).padEnd(5)+"  FR "+pn(f.ph[1]).padEnd(5);
  s+="    EMB cmd: LR "+f.emb[0].toFixed(2)+"  RR "+f.emb[1].toFixed(2);
  hud.textContent=s;
}
function tick(now){
  if(!playing)return;
  const dt=now-lastWall;lastWall=now;
  idx+=(dt/40)*speed;
  if(idx>=frames.length-1){idx=frames.length-1;playing=false;playBtn.textContent="▶ play";}
  redraw();if(playing)requestAnimationFrame(tick);
}
playBtn.addEventListener("click",()=>{
  if(playing){playing=false;playBtn.textContent="▶ play";return;}
  if(idx>=frames.length-1)idx=0;
  playing=true;lastWall=performance.now();playBtn.textContent="⏸ pause";
  requestAnimationFrame(tick);
});
scrub.addEventListener("input",()=>{idx=parseInt(scrub.value,10);redraw();});
speedSel.addEventListener("change",()=>{speed=parseFloat(speedSel.value);});
runSel.addEventListener("change",()=>{setRun(runSel.value);});
stepBack.addEventListener("click",()=>{idx=Math.max(0,Math.floor(idx)-1);redraw();});
stepFwd.addEventListener("click",()=>{idx=Math.min(frames.length-1,Math.floor(idx)+1);redraw();});
setRun("on");
</script></body></html>
"""
    return html.replace("__TEST__", t).replace("__PAYLOAD__", payload_json)


def chart_yaw_rate(rows: list[dict], brake_idx: int, end_idx: int,
                    title: str) -> str:
    svg = Svg(w=720, h=200, title=title)
    if brake_idx < 0:
        svg.axes(0, 1, 0, 1, "t [s]", "yaw rate [rad/s]")
        return svg.render()
    sub = rows[brake_idx:end_idx+1]
    pts = [(r["sim_time_s"], r["yaw_rate"]) for r in sub]
    xs = [p[0] for p in pts]
    ys = [p[1] for p in pts]
    y_max = max(0.05, max(abs(min(ys)), abs(max(ys))) * 1.15)
    ax = svg.axes(min(xs), max(xs), -y_max, y_max,
                  x_label="t [s]", y_label="yaw rate [rad/s]")
    svg.hline(ax, 0, color="#666", dash="1 0")
    svg.polyline(ax, pts, color="#3470c0", width=1.2)
    return svg.render()


def chart_trajectory(on_rows: list[dict], off_rows: list[dict],
                      on_brake: int, on_end: int,
                      off_brake: int, off_end: int,
                      title: str) -> str:
    """pos_x vs pos_y over the brake event.  Most relevant on split_mu."""
    svg = Svg(w=720, h=240, title=title)
    on_pts  = [(r["pos_x"], r["pos_y"])
               for r in on_rows[on_brake:on_end+1]]    if on_brake  >= 0 else []
    off_pts = [(r["pos_x"], r["pos_y"])
               for r in off_rows[off_brake:off_end+1]] if off_brake >= 0 else []
    if not on_pts and not off_pts:
        svg.axes(0, 1, 0, 1, "pos_x [m]", "pos_y [m]")
        return svg.render()
    xs = [p[0] for p in on_pts] + [p[0] for p in off_pts]
    ys = [p[1] for p in on_pts] + [p[1] for p in off_pts]
    # Pad y range a touch and force symmetric so the lateral drift reads
    # cleanly even when the magnitude is small (split_mu is sub-meter).
    y_pad = max(0.5, (max(ys) - min(ys)) * 0.3)
    ax = svg.axes(min(xs), max(xs), min(ys) - y_pad, max(ys) + y_pad,
                  x_label="pos_x [m]", y_label="pos_y [m]")
    svg.hline(ax, 0, color="#aaa", dash="1 0")
    svg.polyline(ax, off_pts, color="#e08a3c", width=1.4)
    svg.polyline(ax, on_pts,  color="#3470c0", width=1.4)
    svg.legend(ax, [("BTCM-on", "#3470c0"), ("BTCM-off", "#e08a3c")])
    return svg.render()


# ---------------------------------------------------------------------------
# Phase-segment statistics
# ---------------------------------------------------------------------------

def phase_stats(rows: list[dict], col: str,
                brake_idx: int, end_idx: int) -> dict:
    """% of brake event spent in APPLY / HOLD / DUMP / stale, plus
    transition count (excluding stale boundaries)."""
    if brake_idx < 0:
        return {"apply": 0.0, "hold": 0.0, "dump": 0.0,
                "stale": 0.0, "transitions": 0}
    durations = {0: 0.0, 1: 0.0, 2: 0.0, -1: 0.0}
    transitions = 0
    prev = int(rows[brake_idx].get(col, -1))
    prev_t = rows[brake_idx]["sim_time_s"]
    for r in rows[brake_idx + 1:end_idx + 1]:
        t = r["sim_time_s"]
        durations[prev] = durations.get(prev, 0.0) + (t - prev_t)
        cur = int(r.get(col, -1))
        if cur != prev and cur != -1 and prev != -1:
            transitions += 1
        prev_t = t
        prev = cur
    total = sum(durations.values())
    if total == 0:
        return {"apply": 0.0, "hold": 0.0, "dump": 0.0,
                "stale": 0.0, "transitions": 0}
    return {
        "apply":       100.0 * durations.get(0,  0.0) / total,
        "hold":        100.0 * durations.get(1,  0.0) / total,
        "dump":        100.0 * durations.get(2,  0.0) / total,
        "stale":       100.0 * durations.get(-1, 0.0) / total,
        "transitions": transitions,
    }


def yaw_drift_deg(rows: list[dict],
                  brake_idx: int, end_idx: int) -> float:
    """Integrate yaw_rate over the brake event → total heading change."""
    import math
    if brake_idx < 0 or brake_idx >= end_idx:
        return 0.0
    drift = 0.0
    for i in range(brake_idx, end_idx):
        dt = rows[i+1]["sim_time_s"] - rows[i]["sim_time_s"]
        drift += rows[i]["yaw_rate"] * dt
    return drift * (180.0 / math.pi)


# ---------------------------------------------------------------------------
# Markdown emitters
# ---------------------------------------------------------------------------

def stop_str(d: dict, prefix: str) -> str:
    if d.get(f"{prefix}_stopped"):
        return f"{d['{}_stop_dist'.format(prefix)]:.2f} m / {d['{}_stop_t'.format(prefix)]:.2f} s"
    if (v := d.get(f"{prefix}_final_v")) is not None:
        return f"didn't stop, v\\_f = {v:.2f} m/s"
    return "—"


def write_scenario_section(t: str, d: dict,
                           on_rows: list[dict], off_rows: list[dict],
                           btcm_rows: list[dict],
                           charts_dir: Path,
                           out_md_dir: Path) -> list[str]:
    """Emit a per-scenario section.  Generates SVG charts in charts_dir
    and references them by relative path from out_md_dir."""
    setup = SETUP[t]
    on_brake, on_end   = find_brake_indices(on_rows)
    off_brake, off_end = find_brake_indices(off_rows)

    fl_phase = phase_stats(on_rows, "abs_phase_fl", on_brake, on_end)
    fr_phase = phase_stats(on_rows, "abs_phase_fr", on_brake, on_end)
    on_yaw   = yaw_drift_deg(on_rows,  on_brake,  on_end)
    off_yaw  = yaw_drift_deg(off_rows, off_brake, off_end)

    def write_svg(name: str, content: str) -> str:
        p = charts_dir / f"{t}_{name}.svg"
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content)
        rel = p.relative_to(out_md_dir)
        return str(rel)

    # Animated top-down replay (HTML).  Self-contained — embeds the
    # frame data + JS + SVG in one file so the user can open it
    # directly from their filesystem.  Carried as a sibling of the
    # SVG charts so the report's link resolves.
    repo_root  = out_md_dir.parent.parent  # docs/reports → repo root
    level_path = repo_root / LEVEL_FILES.get(t, "")
    replay_path = charts_dir / f"{t}_replay.html"
    replay_path.parent.mkdir(parents=True, exist_ok=True)
    replay_path.write_text(make_replay_html(t, on_rows, off_rows, level_path))
    replay_rel = replay_path.relative_to(out_md_dir)

    speed_svg     = write_svg("speed",
                              chart_speed_compare(on_rows, off_rows,
                                                   on_brake, on_end,
                                                   off_brake, off_end,
                                                   f"{t} — vehicle speed during brake event"))
    brakeout_svg  = write_svg("brake_outputs",
                              chart_brake_outputs(on_rows, off_rows,
                                                   on_brake, on_end,
                                                   off_brake, off_end,
                                                   f"{t} — brake commands at chrono (front solid, rear dashed)"))
    wheel_svg     = write_svg("wheel_speed",
                              chart_per_wheel_speed(on_rows, on_brake, on_end,
                                                     f"{t} — chassis vs per-wheel ground speed (BTCM-on)"))
    slip_svg      = write_svg("slip",
                              chart_slip_ratios(on_rows, on_brake, on_end,
                                                 f"{t} — slip ratios (BTCM-on, raw chassis tire-contact data)"))
    phase_svg     = write_svg("phase",
                              chart_abs_phase_timeline(on_rows, on_brake, on_end,
                                                        f"{t} — front ABS phase timeline (BTCM-on, hydraulic)"))
    rear_svg      = write_svg("rear_emb",
                              chart_rear_modulation(on_rows, on_brake, on_end,
                                                     f"{t} — rear EMB motor command (BTCM-on)"))
    actlag_svg    = write_svg("actuator_lag",
                              chart_actuator_lag(on_rows, on_brake, on_end,
                                                  f"{t} — command vs actual actuator state (BTCM-on)"))
    yaw_svg       = write_svg("yaw",
                              chart_yaw_rate(on_rows, on_brake, on_end,
                                              f"{t} — yaw rate during brake event (BTCM-on)"))
    btcm_view_svg = ""
    btcm_accel_svg = ""
    if btcm_rows:
        btcm_view_svg = write_svg("btcm_view",
                                   chart_btcm_internal_view(btcm_rows, on_rows,
                                       f"{t} — BTCM firmware internal view (firmware vs chassis truth)"))
        btcm_accel_svg = write_svg("btcm_accel",
                                    chart_btcm_accel(btcm_rows,
                                        f"{t} — BTCM-side accelerometer reading"))

    lines: list[str] = []
    lines.append(f"## `{t}`")
    lines.append("")
    lines.append("### Setup")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    lines.append(f"| Surface | {setup['surface']} |")
    lines.append(f"| Approach | {setup['approach']} |")
    lines.append(f"| Brake fires | {setup['brake_at']} |")
    lines.append(f"| Validates | {setup['checks']} |")
    lines.append("")

    lines.append("### Result summary (BTCM-on vs BTCM-off)")
    lines.append("")
    lines.append("| Metric | BTCM-on | BTCM-off |")
    lines.append("|---|---|---|")
    lines.append(f"| Brake-on at | t = {d.get('on_brake_t', 0):.2f} s, v = {d.get('on_brake_v', 0):.2f} m/s | t = {d.get('off_brake_t', 0):.2f} s, v = {d.get('off_brake_v', 0):.2f} m/s |")
    lines.append(f"| Stop result | {stop_str(d, 'on')} | {stop_str(d, 'off')} |")
    lines.append(f"| FL events | {d.get('on_fl_events', 0)} | {d.get('off_fl_events', 0)} |")
    lines.append(f"| FR events | {d.get('on_fr_events', 0)} | {d.get('off_fr_events', 0)} |")
    lines.append(f"| Yaw drift over brake | {on_yaw:+.2f}° | {off_yaw:+.2f}° |")
    lines.append("")

    lines.append("### Per-wheel slip statistics (BTCM-on)")
    lines.append("")
    lines.append("| Wheel | peak | mean | time-locked |")
    lines.append("|---|---:|---:|---:|")
    for w in ("fl", "fr", "rl", "rr"):
        lines.append(
            f"| {w.upper()} | {d.get(f'on_{w}_peak', 0):.3f} | "
            f"{d.get(f'on_{w}_mean', 0):.3f} | "
            f"{d.get(f'on_{w}_locked', 0):.1f}% |")
    lines.append("")

    lines.append("### Front ABS phase distribution during brake event (BTCM-on)")
    lines.append("")
    lines.append("| Wheel | APPLY | HOLD | DUMP | stale | phase transitions |")
    lines.append("|---|---:|---:|---:|---:|---:|")
    lines.append(
        f"| FL | {fl_phase['apply']:.1f}% | {fl_phase['hold']:.1f}% | "
        f"{fl_phase['dump']:.1f}% | {fl_phase['stale']:.1f}% | "
        f"{fl_phase['transitions']} |")
    lines.append(
        f"| FR | {fr_phase['apply']:.1f}% | {fr_phase['hold']:.1f}% | "
        f"{fr_phase['dump']:.1f}% | {fr_phase['stale']:.1f}% | "
        f"{fr_phase['transitions']} |")
    lines.append("")

    lines.append("### Charts")
    lines.append("")
    lines.append(f"**[▶ Animated top-down replay (open in browser)]({replay_rel})** — "
                 "watch the car drive through the brake event with per-wheel slip "
                 "color-coded, surface patches drawn behind, and a scrubbable "
                 "timeline.  Toggle BTCM-on / BTCM-off in the dropdown to A/B "
                 "the same instant.")
    lines.append("")
    lines.append("**Vehicle speed**")
    lines.append("")
    lines.append(f"![speed compare]({speed_svg})")
    lines.append("")
    lines.append("**Effective brake force at each axle.**  Front solid,")
    lines.append("rear dashed.  Front line is `applied_front_brake` directly")
    lines.append("(the post-ABS-modulation ratio fed to Chrono).  Rear line")
    lines.append("is *derived* from `emb_cmd_lr/rr`: max(0, cmd) averaged")
    lines.append("across L and R, because the CSV's `applied_rear_brake`")
    lines.append("captures the *symmetric* driver-pedal command rather than")
    lines.append("the per-wheel override that `ApplyRearEmbBrake` feeds into")
    lines.append("Chrono.  BTCM-off rear is forced to 0 here — the EV1's")
    lines.append("rear EMB has no hydraulic backup line, so when the")
    lines.append("controller is out of the loop the rear free-rolls.")
    lines.append("")
    lines.append(f"![brake outputs]({brakeout_svg})")
    lines.append("")
    lines.append("**Front ABS phase timeline (hydraulic axle).**  Discrete")
    lines.append("APPLY/HOLD/DUMP solenoid bands.  See the rear EMB chart")
    lines.append("just below for the *equivalent* rear-axle modulation —")
    lines.append("same algorithm decisions, different actuator (continuous")
    lines.append("motor command in [-1, +1] instead of solenoid phases).")
    lines.append("")
    lines.append(f"![ABS phase timeline]({phase_svg})")
    lines.append("")
    lines.append("**Rear EMB motor command (electromechanical axle).** "
                 "Continuous-valued analog of the front Gantt above. "
                 "`+1` = motor pushing apply, `-1` = motor releasing the "
                 "shoes, `~0` = hold position.")
    lines.append("")
    lines.append(f"![rear EMB cmd]({rear_svg})")
    lines.append("")
    lines.append("**Command vs actual actuator state.**  Solid lines are")
    lines.append("commands sent to Chrono; dashed lines are the modeled")
    lines.append("post-actuator-lag values (caliper hydraulic τ ≈ 50 ms")
    lines.append("apply / 80 ms release; rear shoe rate-limited at ~3.33/s).")
    lines.append("Useful for understanding why ABS modulation looks blunt")
    lines.append("on the speed chart — the actuator lag smooths the rapid")
    lines.append("HOLD↔DUMP cycling into a slower-changing pressure curve.")
    lines.append("")
    lines.append(f"![actuator lag]({actlag_svg})")
    lines.append("")
    lines.append("**Per-wheel ground speed** (chassis line + 4 wheel lines)."
                 "  Gap = slip.")
    lines.append("")
    lines.append(f"![per-wheel speeds]({wheel_svg})")
    lines.append("")
    lines.append("**Slip ratios.**  Threshold reference lines at 0.05 and")
    lines.append("0.15 mark the algorithm's exit / enter slip thresholds.")
    lines.append("Note the chassis-side slip values are *raw tire-contact*")
    lines.append("data from Chrono's TMeasy model and look noisier than a")
    lines.append("real ABS would see — production ABS heavily filters this")
    lines.append("(typically a 10–30 ms low-pass), and our firmware's own")
    lines.append("perception of slip (derived from tone-ring counts over")
    lines.append("50 ms windows) is naturally smoother.  The peaks here")
    lines.append("show what the *tire* is actually doing instant-to-")
    lines.append("instant; the firmware's view is a window-average.")
    lines.append("")
    lines.append(f"![slip ratios]({slip_svg})")
    lines.append("")
    lines.append("**Yaw rate.**  Positive = counter-clockwise rotation.")
    lines.append("")
    lines.append(f"![yaw rate]({yaw_svg})")
    lines.append("")

    if btcm_view_svg:
        lines.append("**BTCM firmware internal view.**  What the AVR's ABS")
        lines.append("algorithm *thinks* is happening, sampled from the")
        lines.append("firmware's `abs_controller_t` state via the host-side")
        lines.append("`BTCM_CSV_LOG` snapshot.  Black = chassis truth (ev1sim);")
        lines.append("blue = firmware's own `vehicle_speed_mps` reference;")
        lines.append("colored = firmware's per-wheel ground speed (rps × tire")
        lines.append("radius).  Time axis aligned to BTCM's brake-on event so")
        lines.append("t=0 here matches t=0 in the chassis charts above.")
        lines.append("Divergences between chassis truth and firmware view")
        lines.append("show where the ABS algorithm's perception is wrong.")
        lines.append("")
        lines.append(f"![BTCM internal view]({btcm_view_svg})")
        lines.append("")
    if btcm_accel_svg:
        lines.append("**BTCM-side accelerometer reading.**  The host bridge")
        lines.append("publishes longitudinal accel onto the chassis bus and")
        lines.append("pokes it into `g_host_sensors` even when the firmware's")
        lines.append("ABS algorithm doesn't consume it (build-time gated by")
        lines.append("`BTCM_USE_ACCELEROMETER`, default OFF to match original")
        lines.append("EV1).  Useful for understanding what a second-gen ABS")
        lines.append("would see if the firmware was rebuilt with the gate on.")
        lines.append("")
        lines.append(f"![BTCM accelerometer]({btcm_accel_svg})")
        lines.append("")

    if t == "split_mu":
        traj_svg = write_svg("trajectory",
                              chart_trajectory(on_rows, off_rows,
                                                on_brake, on_end,
                                                off_brake, off_end,
                                                f"{t} — vehicle trajectory (pos_x vs pos_y)"))
        lines.append("**Trajectory.**  pos_x vs pos_y over the brake event.")
        lines.append("")
        lines.append(f"![trajectory]({traj_svg})")
        lines.append("")

    return lines


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 1
    out_path = Path(argv[1])
    out_md_dir = out_path.parent
    charts_dir = out_md_dir / f"{out_path.stem}.charts"

    parsed: dict[str, dict] = {}
    on_rows_by:   dict[str, list[dict]] = {}
    off_rows_by:  dict[str, list[dict]] = {}
    btcm_rows_by: dict[str, list[dict]] = {}
    missing: list[str] = []
    for t in TESTS:
        d = Path(SUMMARY_DIR_TMPL.format(test=t))
        s = d / "summary.txt"
        on_csv   = d / "abs_btcm_on.csv"
        off_csv  = d / "abs_btcm_off.csv"
        btcm_csv = d / "abs_btcm_on.btcm.csv"
        if not (s.exists() and on_csv.exists() and off_csv.exists()):
            missing.append(t)
            continue
        parsed[t]      = parse_summary(s.read_text())
        on_rows_by[t]  = load_csv(on_csv)
        off_rows_by[t] = load_csv(off_csv)
        btcm_rows_by[t] = load_csv(btcm_csv) if btcm_csv.exists() else []

    if missing:
        for m in missing:
            print(f"warning: missing source data for {m} — re-run "
                  f"scripts/run_abs_compare.sh {m}", file=sys.stderr)

    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M %Z").strip()

    lines: list[str] = []
    lines.append("# EV1 ABS validation — engineering report")
    lines.append("")
    lines.append(f"_Generated {ts} by `scripts/abs_report.py`._")
    lines.append("")
    lines.append("This report aggregates the four standard ABS validation")
    lines.append("scenarios.  Each scenario gets its own section with setup,")
    lines.append("numerical result tables, and a stack of charts: vehicle")
    lines.append("speed, per-wheel ground speed, slip ratios, ABS phase")
    lines.append("timeline, yaw rate, and (for `split_mu`) trajectory.")
    lines.append("")
    lines.append("Source data: `/tmp/ev1sim_abs_<test>/{summary.txt,")
    lines.append("abs_btcm_{on,off}.csv}`.  Refresh with")
    lines.append("`for t in high_mu low_mu mu_jump split_mu; do "
                 "./scripts/run_abs_compare.sh $t; done` and re-run this")
    lines.append("script.")
    lines.append("")

    # Top-of-file summary table.
    lines.append("## Headline table")
    lines.append("")
    lines.append("| Test | BTCM-on stop | BTCM-off stop | Δ stop dist | "
                 "ABS events FL/FR | yaw drift (on / off) |")
    lines.append("|---|---|---|---:|---:|---|")
    import math
    for t in TESTS:
        d = parsed.get(t)
        if d is None:
            lines.append(f"| {t} | (no data) | (no data) | — | — | — |")
            continue
        on  = stop_str(d, "on")
        off = stop_str(d, "off")
        delta = "—"
        if d.get("on_stopped") and d.get("off_stopped"):
            delta = f"{d['on_stop_dist'] - d['off_stop_dist']:+.1f} m"
        on_brake_idx, on_end_idx   = find_brake_indices(on_rows_by[t])
        off_brake_idx, off_end_idx = find_brake_indices(off_rows_by[t])
        on_yaw  = yaw_drift_deg(on_rows_by[t],  on_brake_idx,  on_end_idx)
        off_yaw = yaw_drift_deg(off_rows_by[t], off_brake_idx, off_end_idx)
        lines.append(
            f"| {t} | {on} | {off} | {delta} | "
            f"{d.get('on_fl_events', 0)} / {d.get('on_fr_events', 0)} | "
            f"{on_yaw:+.2f}° / {off_yaw:+.2f}° |")
    lines.append("")
    lines.append("Δ stop dist > 0 means BTCM-on took *longer* than BTCM-off.")
    lines.append("Yaw drift > 0 = car rotated counter-clockwise (toward driver");
    lines.append("left).  On `split_mu` the car drifts toward the asphalt side")
    lines.append("(positive in our coordinate frame).")
    lines.append("")

    # Per-scenario sections.
    for t in TESTS:
        if t not in parsed:
            lines.append(f"## `{t}`")
            lines.append("")
            lines.append("_(no data — re-run `scripts/run_abs_compare.sh "
                         f"{t}` then re-run this script)_")
            lines.append("")
            continue
        lines.extend(write_scenario_section(
            t, parsed[t], on_rows_by[t], off_rows_by[t],
            btcm_rows_by.get(t, []),
            charts_dir, out_md_dir))

    out_path.write_text("\n".join(lines) + "\n")
    print(f"[abs-report] wrote {out_path}")
    print(f"[abs-report] charts → {charts_dir}/")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
